"""
Role-Based Access Control Configuration
Define what each role can access and do
"""

# Define permissions for each role
ROLE_PERMISSIONS = {
    'admin': {
        'can_view_dashboard': True,
        'can_process_sales': True,
        'can_view_all_sales': True,
        'can_view_own_sales_only': False,
        'can_process_returns': True,
        'can_manage_credit': True,
        'can_view_credit': True,
        'can_manage_inventory': True,
        'can_view_inventory': True,
        'can_adjust_stock': True,
        'can_manage_products': True,
        'can_delete_products': True,
        'can_manage_customers': True,
        'can_view_customers': True,
        'can_view_reports': True,
        'can_export_reports': True,
        'can_view_activity_logs': True,
        'can_delete_activity_logs': True,
        'can_manage_users': True,
        'can_create_users': True,
        'can_edit_users': True,
        'can_delete_users': True,
        'can_manage_settings': True,
        'can_manage_backup': True,
        'can_view_audit_trail': True,
        'can_manage_system': True,
    },
    'manager': {
        'can_view_dashboard': True,
        'can_process_sales': True,
        'can_view_all_sales': True,
        'can_view_own_sales_only': False,
        'can_process_returns': True,
        'can_manage_credit': True,
        'can_view_credit': True,
        'can_manage_inventory': True,
        'can_view_inventory': True,
        'can_adjust_stock': True,
        'can_manage_products': True,
        'can_delete_products': False,  # Managers cannot delete products
        'can_manage_customers': True,
        'can_view_customers': True,
        'can_view_reports': True,
        'can_export_reports': True,
        'can_view_activity_logs': True,
        'can_delete_activity_logs': False,
        'can_manage_users': True,  # Can view users but not create/edit/delete
        'can_create_users': False,
        'can_edit_users': False,
        'can_delete_users': False,
        'can_manage_settings': False,
        'can_manage_backup': False,
        'can_view_audit_trail': True,
        'can_manage_system': False,
    },
    'pharmacist': {
        'can_view_dashboard': True,
        'can_process_sales': True,
        'can_view_all_sales': True,
        'can_view_own_sales_only': False,
        'can_process_returns': True,
        'can_manage_credit': False,
        'can_view_credit': False,
        'can_manage_inventory': True,
        'can_view_inventory': True,
        'can_adjust_stock': True,
        'can_manage_products': True,
        'can_delete_products': False,
        'can_manage_customers': True,
        'can_view_customers': True,
        'can_view_reports': True,
        'can_export_reports': False,
        'can_view_activity_logs': False,
        'can_delete_activity_logs': False,
        'can_manage_users': False,
        'can_create_users': False,
        'can_edit_users': False,
        'can_delete_users': False,
        'can_manage_settings': False,
        'can_manage_backup': False,
        'can_view_audit_trail': False,
        'can_manage_system': False,
    },
    'cashier': {
        'can_view_dashboard': True,
        'can_process_sales': True,
        'can_view_all_sales': False,
        'can_view_own_sales_only': True,  # Can only view their own sales
        'can_process_returns': False,
        'can_manage_credit': False,
        'can_view_credit': False,
        'can_manage_inventory': False,
        'can_view_inventory': True,  # Can view but not manage
        'can_adjust_stock': False,
        'can_manage_products': False,
        'can_delete_products': False,
        'can_manage_customers': True,
        'can_view_customers': True,
        'can_view_reports': False,
        'can_export_reports': False,
        'can_view_activity_logs': False,
        'can_delete_activity_logs': False,
        'can_manage_users': False,
        'can_create_users': False,
        'can_edit_users': False,
        'can_delete_users': False,
        'can_manage_settings': False,
        'can_manage_backup': False,
        'can_view_audit_trail': False,
        'can_manage_system': False,
    },
    'auditor': {
        'can_view_dashboard': True,
        'can_process_sales': False,
        'can_view_all_sales': True,
        'can_view_own_sales_only': False,
        'can_process_returns': False,
        'can_manage_credit': False,
        'can_view_credit': True,
        'can_manage_inventory': False,
        'can_view_inventory': True,
        'can_adjust_stock': False,
        'can_manage_products': False,
        'can_delete_products': False,
        'can_manage_customers': False,
        'can_view_customers': True,
        'can_view_reports': True,
        'can_export_reports': True,
        'can_view_activity_logs': True,
        'can_delete_activity_logs': False,
        'can_manage_users': False,
        'can_create_users': False,
        'can_edit_users': False,
        'can_delete_users': False,
        'can_manage_settings': False,
        'can_manage_backup': False,
        'can_view_audit_trail': True,
        'can_manage_system': False,
    },
    'saler': {
        'can_view_dashboard': True,
        'can_process_sales': True,
        'can_view_all_sales': False,
        'can_view_own_sales_only': True,
        'can_process_returns': False,
        'can_delete_sales': False,
        'can_manage_credit': False,
        'can_view_credit': True,
        'can_make_credit_payments': True,
        'can_manage_inventory': False,
        'can_view_inventory': False,
        'can_adjust_stock': False,
        'can_manage_products': False,
        'can_delete_products': False,
        'can_manage_customers': False,
        'can_view_customers': True,
        'can_view_reports': False,
        'can_export_reports': False,
        'can_view_activity_logs': False,
        'can_delete_activity_logs': False,
        'can_manage_users': False,
        'can_create_users': False,
        'can_edit_users': False,
        'can_delete_users': False,
        'can_manage_settings': False,
        'can_manage_backup': False,
        'can_view_audit_trail': False,
        'can_manage_system': False,
    },
}

# Page/URL access control
PAGE_ACCESS = {
    # Sales Pages
    'sales:pos_view': ['admin', 'manager', 'pharmacist', 'cashier', 'saler'],
    'sales:checkout': ['admin', 'manager', 'pharmacist', 'cashier', 'saler'],
    'sales:sale_list': ['admin', 'manager', 'pharmacist', 'cashier', 'auditor', 'saler'],
    'sales:sale_detail': ['admin', 'manager', 'pharmacist', 'cashier', 'auditor', 'saler'],
    'sales:sale_return': ['admin', 'manager', 'pharmacist'],
    'sales:sale_payments': ['admin', 'manager', 'pharmacist', 'cashier', 'saler'],
    'sales:add_partial_payment': ['admin', 'manager', 'pharmacist', 'cashier', 'saler'],
    'sales:edit_payment': ['admin', 'manager', 'saler'],
    'sales:credit_list': ['admin', 'manager', 'auditor', 'saler'],
    'sales:credit_detail': ['admin', 'manager', 'auditor', 'saler'],
    'sales:credit_payment': ['admin', 'manager', 'saler'],
    'sales:customer_list': ['admin', 'manager', 'pharmacist', 'cashier', 'auditor', 'saler'],
    'sales:customer_create': ['admin', 'manager', 'pharmacist', 'cashier'],
    'sales:customer_detail': ['admin', 'manager', 'pharmacist', 'cashier', 'auditor', 'saler'],
    'sales:sales_report': ['admin', 'manager', 'auditor'],
    'sales:sale_update': ['admin', 'manager', 'pharmacist'],
    'sales:sale_delete': ['admin', 'manager'],

    # Inventory Pages (cashier and saler cannot create/edit products or manage purchases)
    'inventory:product_list': ['admin', 'manager', 'pharmacist', 'cashier', 'auditor'],
    'inventory:product_create': ['admin', 'manager', 'pharmacist'],
    'inventory:product_detail': ['admin', 'manager', 'pharmacist', 'cashier', 'auditor'],
    'inventory:product_update': ['admin', 'manager', 'pharmacist'],
    'inventory:product_delete': ['admin', 'manager'],
    'inventory:stock_list': ['admin', 'manager', 'pharmacist', 'auditor', 'cashier'],
    'inventory:stock_movement': ['admin', 'manager', 'pharmacist', 'auditor'],
    'inventory:stock_adjustment': ['admin', 'manager', 'pharmacist'],
    'inventory:stock_alerts': ['admin', 'manager', 'pharmacist', 'auditor'],
    'inventory:low_stock_report': ['admin', 'manager', 'pharmacist', 'auditor'],
    'inventory:expiry_report': ['admin', 'manager', 'pharmacist', 'auditor'],

    # Purchases Pages (cashier and saler cannot access purchases)
    'purchases:purchase_order_list': ['admin', 'manager', 'pharmacist'],
    'purchases:purchase_order_create': ['admin', 'manager', 'pharmacist'],
    'purchases:purchase_order_detail': ['admin', 'manager', 'pharmacist'],
    'purchases:purchase_order_cancel': ['admin', 'manager'],
    'purchases:purchase_order_pdf': ['admin', 'manager', 'pharmacist', 'auditor'],

    # Core Pages
    'core:dashboard': ['admin', 'manager', 'pharmacist', 'cashier', 'auditor', 'saler'],
    'core:activity_logs': ['admin', 'auditor'],
    'core:company_settings': ['admin', 'manager'],
    'core:system_settings': ['admin'],
    'core:backup': ['admin'],

    # Accounts Pages
    'accounts:user_list': ['admin', 'manager'],
    'accounts:user_create': ['admin'],
    'accounts:user_detail': ['admin', 'manager'],
    'accounts:user_edit': ['admin'],
    'accounts:user_delete': ['admin'],
    'accounts:activity_log': ['admin', 'auditor'],
    'accounts:profile': ['admin', 'manager', 'pharmacist', 'cashier', 'auditor', 'saler'],
    'accounts:change_password': ['admin', 'manager', 'pharmacist', 'cashier', 'auditor', 'saler'],
}

def has_permission(user, permission):
    """Check if user has a specific permission"""
    if not user.is_authenticated:
        return False
    if user.is_superuser:
        return True
    role = user.role
    return ROLE_PERMISSIONS.get(role, {}).get(permission, False)

def can_access_page(user, page_name):
    """Check if user can access a specific page"""
    if not user.is_authenticated:
        return False
    if user.is_superuser:
        return True
    allowed_roles = PAGE_ACCESS.get(page_name, [])
    return user.role in allowed_roles