# Generated by Django 6.0.7 on 2026-07-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="color_changes_remaining",
            field=models.IntegerField(
                default=5, help_text="Number of color changes remaining (max 5)"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="e.g. Kariakoo, Dar es salaam, Tanzania",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="p_o_box",
            field=models.CharField(blank=True, max_length=100, verbose_name="P.O.BOX"),
        ),
        migrations.AddField(
            model_name="company",
            name="primary_color",
            field=models.CharField(
                default="#0d5c3a",
                help_text="Primary color for the system and all receipts",
                max_length=7,
            ),
        ),
    ]
