# Generated by Django 6.0.7 on 2026-07-27 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_company_color_changes_remaining_company_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        help_text="e.g. NMB Bank, CRDB Bank", max_length=200
                    ),
                ),
                (
                    "account_name",
                    models.CharField(help_text="Account holder name", max_length=200),
                ),
                (
                    "account_number",
                    models.CharField(help_text="Bank account number", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "bank_name"],
            },
        ),
    ]
