# Generated by Django 6.0.7 on 2026-08-01 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a category for frequent/recurring expenses. Leave empty for one-off expenses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.expensecategory'),
        ),
    ]
