# Generated by Django 6.0.7 on 2026-07-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseorder_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
