# Generated by Django 6.0.7 on 2026-07-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fix_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier'), ('auditor', 'Auditor'), ('saler', 'Saler')], default='cashier', max_length=20),
        ),
    ]
