# Generated by Django 6.0.3 on 2026-04-08 03:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="FontAwesome icon class", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "generic_name",
                    models.CharField(
                        blank=True,
                        help_text="Generic name for medicines",
                        max_length=200,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Stock Keeping Unit",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("medicine", "Medicine"),
                            ("equipment", "Medical Equipment"),
                            ("consumable", "Consumable"),
                            ("cosmetic", "Cosmetic"),
                            ("other", "Other"),
                        ],
                        default="medicine",
                        max_length=20,
                    ),
                ),
                (
                    "pack_size",
                    models.CharField(
                        blank=True,
                        help_text="Pack size description (e.g., 100 tablets, 30 capsules, 250ml bottle)",
                        max_length=100,
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=18,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "reorder_level",
                    models.IntegerField(
                        default=10, help_text="Alert when stock falls below this level"
                    ),
                ),
                (
                    "reorder_quantity",
                    models.IntegerField(default=100, help_text="Quantity to reorder"),
                ),
                (
                    "max_stock_level",
                    models.IntegerField(
                        blank=True, help_text="Maximum stock limit", null=True
                    ),
                ),
                ("current_stock", models.IntegerField(default=0)),
                ("minimum_stock", models.IntegerField(default=5)),
                ("maximum_stock", models.IntegerField(default=500)),
                (
                    "unit",
                    models.CharField(
                        default="piece",
                        help_text="Unit of measurement (e.g., tablet, bottle, box)",
                        max_length=20,
                    ),
                ),
                (
                    "prescription_required",
                    models.CharField(
                        choices=[
                            ("none", "No Prescription Required"),
                            ("prescription", "Prescription Required"),
                            ("controlled", "Controlled Substance"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "is_controlled",
                    models.BooleanField(
                        default=False, help_text="Is this a controlled substance?"
                    ),
                ),
                ("requires_license", models.BooleanField(default=False)),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "ingredients",
                    models.TextField(blank=True, help_text="Active ingredients"),
                ),
                ("dosage", models.CharField(blank=True, max_length=200)),
                ("side_effects", models.TextField(blank=True)),
                ("storage_conditions", models.CharField(blank=True, max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_prescription", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="inventory.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "adjustment_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("damage", "Damaged Goods"),
                            ("expiry", "Expired Products"),
                            ("theft", "Theft/Loss"),
                            ("miscount", "Miscount"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("previous_quantity", models.IntegerField()),
                ("new_quantity", models.IntegerField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("current_value", models.IntegerField(help_text="Current stock")),
                ("threshold_value", models.IntegerField(help_text="Alert threshold")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="inventory.product",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("sale", "Sale"),
                            ("return", "Return"),
                            ("adjustment", "Adjustment"),
                            ("transfer", "Transfer"),
                            ("expired", "Expired"),
                            ("damaged", "Damaged"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("previous_quantity", models.IntegerField(default=0)),
                ("new_quantity", models.IntegerField(default=0)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Sale, Purchase Order",
                        max_length=50,
                    ),
                ),
                ("reference_id", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="inventory_p_sku_f85905_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["barcode"], name="inventory_p_barcode_3a77e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="inventory_p_name_f6a6a1_idx"),
        ),
    ]
