# Generated by Django 6.0.3 on 2026-04-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="reorder_level",
            field=models.IntegerField(
                default=2, help_text="Alert when stock falls below this level"
            ),
        ),
    ]
