# Generated by Django 6.0.7 on 2026-07-17 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_reorder_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_controlled',
        ),
        migrations.RemoveField(
            model_name='product',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='requires_license',
        ),
        migrations.RemoveField(
            model_name='product',
            name='side_effects',
        ),
        migrations.AlterField(
            model_name='product',
            name='maximum_stock',
            field=models.IntegerField(default=5000000000),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
