# Generated by Django 6.0.7 on 2026-07-17 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_controlled',
            field=models.BooleanField(default=False, help_text='Is this a controlled substance?'),
        ),
        migrations.AddField(
            model_name='product',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='side_effects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
