# Generated by Django 6.0.7 on 2026-07-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_stockalert_alert_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufacturing_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
