# Generated by Django 6.0.7 on 2026-07-17 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='sales_custo_phone_43e3c6_idx',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='alternative_phone',
            new_name='phone_number_2',
        ),
        migrations.AddField(
            model_name='customer',
            name='fin',
            field=models.CharField(blank=True, max_length=50, verbose_name='FIN'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tin',
            field=models.CharField(blank=True, max_length=50, verbose_name='TIN'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='sales_custo_phone_n_2cfbb3_idx'),
        ),
    ]
