# Generated by Django 6.0.7 on 2026-07-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_customer_address_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='pack_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
