# Generated by Django 6.0.7 on 2026-07-20 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_saleitem_batch_number_saleitem_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='prescription_image',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='prescription_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='prescription_required',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='pack_size',
        ),
    ]
