# Generated by Django 6.0.7 on 2026-07-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_sale_prescription_image_sale_prescription_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[
                    ("proforma", "Proforma Invoice"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
